### Input
# input text prompt (default to None, can be input in GUI too)
prompt: "A 3D model of a futuristic car"
negative_prompt: "ugly, bad anatomy, blurry, pixelated, obscure, unnatural colors, poor lighting, dull, unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh: null
# estimated elevation angle for input image
elevation: 0
# reference image resolution
ref_size: 256
# density threshold for mesh extraction
density_thresh: 1

### Output
outdir: logs
mesh_format: obj
save_path: generated_mesh.obj

### Training
# Specify the use of shap-e model
shap_e: True
# guidance loss weights (0 to disable)
lambda_sd: 1
lambda_shap_e: 1
# training batch size per iter
batch_size: 1
# training iterations
iters: 1000
# whether to linearly anneal timestep
anneal_timestep: True
# training camera radius
radius: 3.5
# training camera fovy
fovy: 49.1
# training camera min elevation
min_ver: -30
# training camera max elevation
max_ver: 30
# checkpoint to load for model (should be a ply file)
load: null
# whether to allow geom training
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.5

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Additional Parameters for shap-e
latent_dim: 512
device: cuda

